apps/adm_test/urls.py
from django.conf.urls import url 
#views.
from .views.v_Program_Test import list_Program_Test,add_Program_Test,update_Program_Test,deleteProgram_Test
from .views.v_Test_Programed import list_Test_Programed,add_Test_Programed,update_Test_Programed,deleteTest_Programed
from .views.v_TestPsicologico import list_TestPsicologico,add_TestPsicologico,update_TestPsicologico,deleteTestPsicologico
from .views.v_History_test_Patient import list_History_test_Patient,add_History_test_Patient,\
  update_History_test_Patient,deleteHistory_test_Patient,list_Patient_json
#.

urlpatterns = [  

  # Program_Test
  url(r'^adm_test/Program_Test/listar/$', list_Program_Test.as_view()),
  url(r'^adm_test/Program_Test/add/$', add_Program_Test.as_view()),
  url(r'^adm_test/Program_Test/update/(?P<pk>\d+)/$', update_Program_Test.as_view()),
  url(r'^adm_test/Program_Test/delete/(?P<id>\d+)/$', deleteProgram_Test),

  # Test_Programed
  url(r'^adm_test/Test_Programed/listar/$', list_Test_Programed.as_view(), name='Test_Programed'),
  url(r'^adm_test/Test_Programed/add/$', add_Test_Programed.as_view()),
  url(r'^adm_test/Test_Programed/update/(?P<pk>\d+)/$', update_Test_Programed.as_view()),
  url(r'^adm_test/Test_Programed/delete/(?P<id>\d+)/$', deleteTest_Programed),

  # TestPsicologico
  url(r'^adm_test/TestPsicologico/listar/$', list_TestPsicologico.as_view()),
  url(r'^adm_test/TestPsicologico/add/$', add_TestPsicologico.as_view(),name='addTestPsicologico'),
  url(r'^adm_test/TestPsicologico/update/(?P<pk>\d+)/$', update_TestPsicologico.as_view()),
  url(r'^adm_test/TestPsicologico/delete/(?P<id>\d+)/$', deleteTestPsicologico),

  # History_test_Patient
  url(r'^adm_test/History_test_Patient/listar/$', list_History_test_Patient.as_view(), name='list_History_test_Patient'),
  url(r'^adm_test/History_test_Patient/add/$', add_History_test_Patient.as_view(), name='add_History_test_Patient'),
  url(r'^adm_test/History_test_Patient/update/(?P<pk>\d+)/$', update_History_test_Patient.as_view(), name='update_History_test_Patient'),
  url(r'^adm_test/History_test_Patient/delete/(?P<id>\d+)/$', deleteHistory_test_Patient, name='delete_History_test_Patient'),

  url(r'^adm_test/History_test_Patient/list_json/$', list_Patient_json.as_view()),
]

config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.security.urls')),
    url(r'^', include('apps.reportes.urls')),
    url(r'^', include('apps.test_psyco.urls')),
  url(r'^', include('apps.adm_institucion.urls')),
  url(r'^', include('apps.adm_test.urls')),
  url(r'^', include('apps.adm_assistance.urls')),
url(r'^', include('apps.adm_security.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/adm_test/models.py
from datetime import datetime

from django.db import models

from apps.security.core.core import TimeStampedModel
from apps.test_psyco.models import TestPsicologico


# Create your models here.
class Program_Test(TimeStampedModel):
    description    =models.CharField(max_length=250)
    start_date     =models.DateField()
    end_date       =models.DateField()
    programmer     =models.ForeignKey('adm_security.Users', related_name='programmer_test', null=True, blank=True, on_delete=models.CASCADE)
    ie             =models.ForeignKey('adm_institucion.Institucion', on_delete=models.CASCADE)
    test           =models.ManyToManyField(TestPsicologico,through='Test_Programed', blank=True)

    def __str__(self):
        if self.status:
            return self.description



class Test_Programed(TimeStampedModel):
    program_test= models.ForeignKey(Program_Test, on_delete=models.CASCADE)
    test        = models.ForeignKey(TestPsicologico, on_delete=models.CASCADE)
    date        = models.DateField()
    time        = models.TimeField()
    patient     = models.ManyToManyField('adm_security.Users', through='History_test_Patient', blank=True)

    def __str__(self):
        return str(self.test)

    @property
    def is_past_due(self):
        #print(datetime.datetime.now() >= self.date)
        d = str(self.date)+" "+str(self.time)
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")>d




class History_test_Patient(TimeStampedModel):
    patient         = models.ForeignKey('adm_security.Users', on_delete=models.CASCADE)
    test_programed  = models.ForeignKey(Test_Programed, on_delete=models.CASCADE)
    date_aplication = models.DateTimeField(auto_now=True)
    status_test = models.CharField(default="No Realizado",max_length=20,choices=(
        ('Realizado','Realizado'),
        ('No Realizado', 'No Realizado'),
        ('Interrumpido','Interrumpido')
    ), blank=True)

    def __get__patient__(self,kwargs):
        context = {
            'status':True,
        }
        context.update(kwargs)
        return History_test_Patient.objects.filter(**context)

    def __test__programed__byusers__(self):
        p = Program_Test.objects.filter(status=True,ie=self.request.session['institucion']['id']).order_by('-id')
        #t = Test_Programed.objects.filter(status=True).order_by('-id')
        h = History_test_Patient.objects.filter(status=True).order_by('-id')
        #get test asignaded a user
        l = []
        for i in p:
            li = {'test_programed__program_test__id': i.id,'patient':self.request.user.id}
            test = h.filter(**li)
            l.append(
                {'program':i,
                 'test':test
                }
            )

        return (l)

apps/adm_test/forms/f_History_test_Patient.py
from django import forms
from ..models import History_test_Patient

class History_test_PatientForm(forms.ModelForm):
  class Meta():
    model = History_test_Patient
    fields = '__all__'
    exclude = ('status', 'deleted_at')
    labels ={
      'patient': 'Paciente',
      'status_test' : 'Estado',
    }

apps/adm_test/forms/f_Program_Test.py
from django import forms
from ..models import Program_Test

class Program_TestForm(forms.ModelForm):
  class Meta():
    model = Program_Test
    fields = '__all__'
    exclude = ('status', 'deleted_at','ie','programmer')
    widgets ={
      'start_date' : forms.DateInput(format=('%Y-%m-%d'), attrs={'type': 'date','placeholder': 'dd/mm/aaaa'}),
      'end_date': forms.DateInput(format=('%Y-%m-%d'), attrs={'type': 'date', 'placeholder': 'dd/mm/aaaa'}),
    }
    labels ={
      'description': 'Descripción',
      'start_date' : 'Fecha de Inicio',
      'end_date'   : 'Fecha de Término'
    }

apps/adm_test/forms/f_TestPsicologico.py
from django import forms
from ..models import TestPsicologico

class TestPsicologicoForm(forms.ModelForm):
  class Meta():
    model = TestPsicologico
    fields = '__all__'
    exclude = ('status', 'deleted_at')

apps/adm_test/forms/f_Test_Programed.py
from django import forms
from ..models import Test_Programed
from apps.test_psyco.models import TestPsicologico

class Test_ProgramedForm(forms.ModelForm):
  def __init__(self, *args, **kwargs):
    super(Test_ProgramedForm, self).__init__(*args, **kwargs)
    #self.fields['test'] = forms.ChoiceField(choices=)

  class Meta():
    model = Test_Programed
    fields = '__all__'
    exclude = ('status', 'deleted_at')
    widgets ={
      'date' : forms.DateInput(format=('%Y-%m-%d'), attrs={'type': 'date','placeholder': 'dd/mm/aaaa'}),
      'time': forms.DateInput(format=('%H:%m'), attrs={'type': 'time', 'placeholder': 'HH:MM'}),
    }
    labels ={
      'date' : 'Fecha del test',
      'time': 'Hora del test',
      'program_test': 'Programa',
      'patient': 'Pacientes'
    }

apps/adm_test/views/v_History_test_Patient.py
from apps.security.core.join_list import validate_dict
from apps.adm_test.templatetags.tags import get_patient
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponse

from apps.security.core.crud import ListBase, SaveBase, UpdateBase,ResponseView
from ..forms.f_History_test_Patient import History_test_PatientForm
from ..models import History_test_Patient


class list_History_test_Patient(ListBase):
  template_name = 'History_test_Patient/list_History_test_Patient.html'

  def l_queryset(self):
    arg = {}
    if self.request.GET:
      arg = validate_dict(self.request.GET)
    arg['status'] = True

    return History_test_Patient.objects.filter(**arg).order_by('-id')

class add_History_test_Patient(SaveBase):
  form_class = History_test_PatientForm
  template_name = 'History_test_Patient/frm_History_test_Patient.html'

class update_History_test_Patient(UpdateBase):
  form_class = History_test_PatientForm
  template_name = 'History_test_Patient/frm_History_test_Patient.html'
  model = History_test_Patient

class list_Patient_json(ResponseView):
  def l_queryset(self):
    return get_patient(self.request.GET.get("idp"))

  def response(self, context):
    return self.response_json()

@login_required(login_url='login/')
def deleteHistory_test_Patient(em, id):
  dp = History_test_Patient.objects.get(pk=id)
  dp.status = False
  dp.save()
  return HttpResponse('DATOS ELIMINADOS')

apps/adm_test/views/v_Program_Test.py
from apps.security.core.join_list import validate_dict
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import HttpResponse

from apps.security.core.crud import ListBase, SaveBase, UpdateBase
from ..forms.f_Program_Test import Program_TestForm
from ..forms.f_Test_Programed import Test_ProgramedForm
from ..models import Program_Test, Test_Programed


class list_Program_Test(ListBase):
  template_name = 'Program_Test/list_Program_Test.html'

  def l_queryset(self):
    queryset = Program_Test.objects.filter(status=True)
    return queryset


class add_Program_Test(SaveBase):
  form_class = Program_TestForm
  form_class2 = Test_ProgramedForm
  template_name = 'Program_Test/frm_Program_Test.html'

  def save_test_pogramed(self,c,ss):
    nl = validate_dict(c)
    nl['program_test'] = ss.id
    form = self.form_class2(nl)
    if form.is_valid():
      fff = form.save(commit=False)
      fff.save()
    else:
      return self.form_invalid(form)

  def form_valid(self, form):
    ss = form.save(commit=False)
    ss.ie_id = int(self.request.session["institucion"]["id"])
    ss.programmer_id = self.request.user.id
    ss.save()

    if self.request.POST.get('m2m') is not None:
      lis = eval(self.request.POST.get('m2m'))
      if type(lis) == "<class 'list'>":
        for c in lis:
          self.save_test_pogramed(c, ss)
      else:
        self.save_test_pogramed(lis, ss)

    return HttpResponseRedirect(self.get_success_url())

class update_Program_Test(UpdateBase):
  form_class = Program_TestForm
  form_class2 = Test_ProgramedForm
  template_name = 'Program_Test/frm_Program_Test.html'
  model = Program_Test
  model2 = Test_Programed

  def l_queryset(self,p):
    q = self.model2.objects.filter(program_test_id=self.kwargs["pk"])
    return q

  def form_valid(self, form):
    ss = form.save(commit=False)
    ss.save()

    if self.request.POST.get('m2m') is not None:
        q = self.l_queryset('')
        idmf = [a.id for a in q]

        mf = []
        for c in eval(self.request.POST.get('m2m')):
          y = validate_dict(c)
          y['program_test'] = ss.id
          if "id" in y:
            mf.append(int(y["id"]))
            if int(y["id"]) in idmf:
              self.model2.objects.filter(pk=y["id"]).update(**y)
          else:
            form = self.form_class2(y)
            if form.is_valid():
              fff = form.save(commit=False)
              fff.save()
            else:
              return self.form_invalid(form)

        for a in idmf:
          if not (a in mf):
            self.model2.objects.get(pk=a).delete()

        return HttpResponseRedirect(self.get_success_url())

@login_required(login_url='login/')
def deleteProgram_Test(em, id):
  dp = Program_Test.objects.get(pk=id)
  dp.status = False
  dp.save()
  return HttpResponse('DATOS ELIMINADOS') 

apps/adm_test/views/v_TestPsicologico.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponse

from apps.security.core.crud import ListBase, SaveBase, UpdateBase
from ..forms.f_TestPsicologico import TestPsicologicoForm
from ..models import TestPsicologico


class list_TestPsicologico(ListBase):
  template_name = 'TestPsicologico/list_TestPsicologico.html'
  queryset = TestPsicologico.objects.filter(status=True)

class add_TestPsicologico(SaveBase):
  form_class = TestPsicologicoForm
  template_name = 'TestPsicologico/frm_TestPsicologico.html'

class update_TestPsicologico(UpdateBase):
  form_class = TestPsicologicoForm
  template_name = 'TestPsicologico/frm_TestPsicologico.html'
  model = TestPsicologico

@login_required(login_url='login/')
def deleteTestPsicologico(em, id):
  dp = TestPsicologico.objects.get(pk=id)
  dp.status = False
  dp.save()
  return HttpResponse('DATOS ELIMINADOS') 

apps/adm_test/views/v_Test_Programed.py
from apps.security.core.join_list import validate_dict
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import HttpResponse

from apps.adm_institucion.models import Classroom, directives
from apps.security.core.crud import ListBase, SaveBase, UpdateBase
from ..forms.f_Test_Programed import Test_ProgramedForm
from ..models import Test_Programed, History_test_Patient


class list_Test_Programed(ListBase):
  template_name = 'Test_Programed/list_Test_Programed.html'

  def l_queryset(self):
    arg = {}
    if self.request.GET:
      arg = validate_dict(self.request.GET)
    arg['status'] = True

    return Test_Programed.objects.filter(**arg).order_by('-id')

class add_Test_Programed(SaveBase):
  form_class = Test_ProgramedForm
  template_name = 'Test_Programed/frm_Test_Programed.html'

  def get_context_data(self, **kwargs):
    context = super(add_Test_Programed, self).get_context_data(**kwargs)
    u =  Classroom.__get__data__ie__(self,{})
    d = directives.__get__data__directive__(self, {})
    l = u
    li = {}
    for i in d:
      a= str(i.occupation)
      if a in li.keys():
        li[a].append(i.directive)
      else:
        li[a] = [i.directive]

    nli=[]
    i = 100
    for j in li.keys():
      i= i+1
      nli.append({'id':i,'name':j,'directives':li[j]})
    context['dir'] = nli

    context['patient'] = l
    return context

  def form_valid(self, form):
    te = form.save(commit=False)
    #te.test_id = form.cleaned_data.get('test')
    te.save()
    for pa in form.cleaned_data.get('patient'):
        h = History_test_Patient(patient=pa, test_programed=te)
        h.save()

    #form.save_m2m()
    return HttpResponseRedirect(self.get_success_url())


class update_Test_Programed(UpdateBase):
  form_class = Test_ProgramedForm
  template_name = 'Test_Programed/frm_Test_Programed.html'

  model = Test_Programed

  def form_valid(self, form):
    te = form.save(commit=False)
    te.save()
    obj = History_test_Patient.objects
    queryset = obj.filter(test_programed=te, status=True)
    patients_data = []
    patients_request = form.cleaned_data['patient']
    for a in queryset:
      patients_data.append(a.patient)
      if not (a.patient in patients_request):
        queryset.filter(patient_id=a.patient_id).delete()

    for i in patients_request:
       if not (i in patients_data):
          obj.create(patient=i, test_programed=te)

    return HttpResponseRedirect(self.get_success_url())

  def get_context_data(self, **kwargs):
    context = super(update_Test_Programed, self).get_context_data(**kwargs)
    u =  Classroom.__get__data__ie__(self,{})
    d = directives.__get__data__directive__(self, {})
    context['patient'] = u
    li = {}
    for i in d:
      a= str(i.occupation)
      if a in li.keys():
        li[a].append(i.directive)
      else:
        li[a] = [i.directive]

    nli=[]
    i = 100
    for j in li.keys():
      i= i+1
      nli.append({'id':i,'name':j,'directives':li[j]})
    context['dir'] = nli


    return context


@login_required(login_url='login/')
def deleteTest_Programed(em, id):
  dp = Test_Programed.objects.get(pk=id)
  dp.status = False
  dp.save()
  return HttpResponse('DATOS ELIMINADOS') 

apps/adm_test/templates/Program_Test/frm_Program_Test.html
<style>
        @media only screen and (max-width: 760px) {
        #id_date{
            margin-left: -105%;
        }
        }
</style>
<div class="card-panel">
        <div class="col s12 m2 l12">
            <h4 align='center' style="color: #2a95a2;text-shadow: 0px 0px 1px rgba(0, 16, 44, 0.86)">{{ name|upper }} PROGRAMA </h4>
            <a onclick='atras()' style='color: #2a95a2;text-shadow: 0px 0px 1px rgba(0, 16, 44, 0.86); cursor: pointer'>
              <i class='fa fa-backward'></i>
              Atras
            </a>
        </div>


    <div class='row'>
        <div class="container">
            <form onsubmit="save_maintenance(this,{% if request.GET.id %}{{request.GET.id }}{% else %}''{% endif %},'Program_Test','adm_test' );return false;"
      >
        {% csrf_token %}
        <div class='col s12 m3 l3'>
          <div class='input-field'>
            {{ form.description }}
            {{ form.description.label_tag }}
          </div>
        </div>
        <div class='col s12 m3 l3'>
          <div class='input-field'>
            {{ form.start_date }}
            {{ form.start_date.label_tag }}
          </div>
        </div>
        <div class='col s12 m3 l3'>
          <div class='input-field'>
            {{ form.end_date }}
            {{ form.end_date.label_tag }}
          </div>
        </div>
            <div class="row m2m" >
                <div class="col s12 m12 l12">
                     <h4 align="center" style="color: #2a95a2;text-shadow: 0px 0px 1px rgba(0, 16, 44, 0.86)"><b>SELECCIONAR O AGREGAR TEST</b></h4>
                    <a class="btn-floating btn-small waves-effect waves-light green" onclick="add_row()">
                        <i class="material-icons">add</i>
                    </a> Agregar Celda
                    <br>
                    <fieldset>
                        <table class="table table-hover table-condensed responsive-table">
                        <thead>
                            <tr>
                                <th><b style="color: rgba(162, 43, 105, 0.82)">Test</b></th>
                                <th><b style="color: rgba(162, 43, 105, 0.82)">Fecha</b></th>
                                <th><b style="color: rgba(162, 43, 105, 0.82)">Hora</b></th>
                            </tr>
                        </thead>
                        <tbody>
                           {% for form2,id in form2 %}
                           <tr>
                               <td>
                                   <div class="row date_l" style="margin-top: -5px;">
                                     <div class="col s12 m12 l12">
                                         {% if id %}
                                             <input type="hidden" name="id" value="{{ id }}">
                                         {% endif %}

                                        {{ form2.test }}
                                         <a onclick="addF(this,'{% url 'addTestPsicologico'  %}','ided')"
                                              class="fa fa-plus-circle"
                                              id="add_more"></a>
                                     </div>
                                    </div>
                               </td>
                               <td>{{ form2.date }}</td>
                               <td>{{ form2.time }}</td>
                               <td>
                                   <a style="color: red; cursor: pointer;" id="elim_nose" onclick="delete_row(this)">
                                       <i class="fa fa-trash fa-2x puntero"></i>
                                   </a>
                               </td>
                           </tr>
                           {% endfor %}
                        </tbody>

                    </table>
                    </fieldset>
                </div>
            </div>
        <div class='col s12' align='center'>
          <button type='submit' class='waves-effect waves-light btn' id='btn_envio'>
            <i class='material-icons'>send</i>{{ name }}
          </button>
        </div>
      </form>
        </div>
    </div>

</div>
<!-- Modal -->
<div id='myModal'> </div>
<script>
    if ($('select option[value=""]').is(':selected')) {
        $("select").append($('<option>', {
            value: '',
            text: '--->seleccione<----'
        })).val('');
    }
    $('select option[value=""]').text('--->seleccione<----');
    $('select').select2({width: '100%'});
    $("label").addClass('active').attr({'data-error':'Correcto','data-success':'Incorrecto'});
    M.updateTextFields();
</script>

apps/adm_test/templates/Program_Test/list_Program_Test.html
    <div class="col s12 m12 l12">
        <h4 align='center' style='color: #3293a2'><b>LISTA DE PROGRAMACIONES</b></h4>
        <a onclick='atras()' style='color: rgb(6, 107, 123); cursor: pointer'>
          <i class='fa fa-backward'></i>
          Atras
        </a>
    </div>


<div class='card'>
  <div class='card-content'>
  <a type='button' class='btn btn-primary' href='#adm_test/Program_Test/add?id='>Agregar</a>
    <table class="table table-striped table-hover table-condensed responsive-table">
      <thead>
        <tr>
          <td>#</td>
          <td>Descripción</td>
          <td>Fecha</td>
          <td>Test Programados</td>
          <td>Creado por:</td>
          <td>Editar</td>
          <td>Eliminar</td>
        </tr>
      </thead>
    <tbody>
      {% for foo in object_list %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ foo.description}}</td>
          <td>{{ foo.start_date|date:'d/m/Y'}} al {{ foo.end_date|date:'d/m/Y'}}</td>
          <td>
              <a href="#{% url 'Test_Programed' %}?program_test={{ foo.id }}">Ver</a>
          </td>
          <td>{{ foo.programmer}}</td>
          <td>
            <a style='color: red' href='#adm_test/Program_Test/update/{{ foo.id}}/?id={{ foo.id}}'>
              <i class='fa fa-pencil-square-o'></i>
            </a>
          </td>
          <td>
            <a style='color: red' onclick="delete_maintenance('adm_test','Program_Test',{{ foo.id}})" style='cursor: pointer'>
              <i class='fa fa-trash puntero'></i>
            </a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>